name: Deploy Jasmin Catering AI Container App

on:
  push:
    branches: [ main, fix/container-apps-email-processing ]
  pull_request:
    branches: [ main ]

env:
  REGISTRY_NAME: jasmincateringregistry
  RESOURCE_GROUP: logicapp-jasmin-sweden_group
  CONTAINER_APP_JOB: jasmin-email-processor
  REGION: swedencentral

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Log in to Azure Container Registry
      run: az acr login --name ${{ env.REGISTRY_NAME }}

    - name: Set image tag
      id: image-tag
      run: |
        if [ "${{ github.event_name }}" = "pull_request" ]; then
          TAG="pr-${{ github.event.number }}-$(date +%Y%m%d-%H%M)"
        else
          TAG="main-$(date +%Y%m%d-%H%M)"
        fi
        echo "IMAGE_TAG=$TAG" >> $GITHUB_OUTPUT
        echo "Full image: ${{ env.REGISTRY_NAME }}.azurecr.io/jasmin-catering-ai:$TAG"

    - name: Build and push container image
      run: |
        IMAGE_NAME="${{ env.REGISTRY_NAME }}.azurecr.io/jasmin-catering-ai:${{ steps.image-tag.outputs.IMAGE_TAG }}"
        echo "Building image: $IMAGE_NAME"
        
        az acr build \
          --registry ${{ env.REGISTRY_NAME }} \
          --image jasmin-catering-ai:${{ steps.image-tag.outputs.IMAGE_TAG }} \
          --file Dockerfile \
          .

    - name: Deploy to Container Apps Job (main branch only)
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: |
        if [ -z "${{ secrets.AZURE_CREDENTIALS }}" ]; then
          echo "⚠️ WARNING: AZURE_CREDENTIALS secret is missing!"
          echo "🚫 Deployment and testing steps will be skipped"
          echo "📋 To enable CI/CD deployment:"
          echo "1. Create Azure Service Principal (requires admin privileges)"
          echo "2. Add AZURE_CREDENTIALS secret to GitHub repository"
          echo "3. See: scripts/utilities/GITHUB_SECRETS_SETUP.md"
          exit 0
        fi
        
        IMAGE_NAME="${{ env.REGISTRY_NAME }}.azurecr.io/jasmin-catering-ai:${{ steps.image-tag.outputs.IMAGE_TAG }}"
        echo "Deploying image: $IMAGE_NAME"
        
        # Update Container Apps Job with new image
        az containerapp job update \
          --name ${{ env.CONTAINER_APP_JOB }} \
          --resource-group ${{ env.RESOURCE_GROUP }} \
          --image "$IMAGE_NAME"
        
        echo "✅ Container Apps Job updated successfully"

    - name: Set up Python for testing
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install Python dependencies for testing
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: |
        python -m pip install --upgrade pip
        pip install python-dotenv

    - name: Run automated deployment test
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      env:
        FROM_EMAIL_ADDRESS: ${{ secrets.FROM_EMAIL_ADDRESS }}
        WEBDE_APP_PASSWORD: ${{ secrets.WEBDE_APP_PASSWORD }}
        AZURE_RESOURCE_GROUP: ${{ env.RESOURCE_GROUP }}
        CONTAINER_APP_JOB: ${{ env.CONTAINER_APP_JOB }}
      run: |
        if [ -z "${{ secrets.AZURE_CREDENTIALS }}" ]; then
          echo "⚠️ Skipping tests - AZURE_CREDENTIALS not available"
          exit 0
        fi
        echo "🧪 Running automated deployment test..."
        python scripts/testing/test_deployment.py

    - name: Upload test report
      if: always() && github.ref == 'refs/heads/main' && github.event_name == 'push'
      uses: actions/upload-artifact@v3
      with:
        name: deployment-test-report
        path: deployment_test_report.json

    - name: Output deployment summary
      run: |
        echo "## 🚀 Deployment Summary" >> $GITHUB_STEP_SUMMARY
        echo "- **Image**: ${{ env.REGISTRY_NAME }}.azurecr.io/jasmin-catering-ai:${{ steps.image-tag.outputs.IMAGE_TAG }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Resource Group**: ${{ env.RESOURCE_GROUP }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Container Apps Job**: ${{ env.CONTAINER_APP_JOB }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Region**: ${{ env.REGION }}" >> $GITHUB_STEP_SUMMARY
        
        if [ "${{ github.ref }}" = "refs/heads/main" ] && [ "${{ github.event_name }}" = "push" ]; then
          if [ -n "${{ secrets.AZURE_CREDENTIALS }}" ]; then
            echo "- **Status**: ✅ Deployed with automated testing" >> $GITHUB_STEP_SUMMARY
            echo "- **Test Email**: ma3u-test@email.de" >> $GITHUB_STEP_SUMMARY
            echo "- **Test Report**: Check artifacts for deployment_test_report.json" >> $GITHUB_STEP_SUMMARY
          else
            echo "- **Status**: ⚠️ Built only - AZURE_CREDENTIALS missing" >> $GITHUB_STEP_SUMMARY
            echo "- **Setup**: See scripts/utilities/GITHUB_SECRETS_SETUP.md" >> $GITHUB_STEP_SUMMARY
            echo "- **Required**: Azure Service Principal (admin privileges needed)" >> $GITHUB_STEP_SUMMARY
          fi
        else
          echo "- **Status**: 🔨 Built only (not deployed - not main branch)" >> $GITHUB_STEP_SUMMARY
        fi